overblog_graphql_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/multiple.yaml"

# overblog_graphql_endpoint:
#     resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"
#     prefix: /graphql