Comment:
  type: object
  config:
    description: "Comment" 
    fields:
      id:
        type: String!
        description: "The ID of the Comment"
      create_date:
        type: DateTime
        description: "Create date"
      last_update:
        type: DateTime
        description: "last update date"
      delete_date:
        type: DateTime
        description: "Delete date"
      comment:
        type: String
        description: "Comment"
      text:
        type: Text
        description: "Text Belongs to"
      created_by:
        type: User
        description: "created by"
      updated_by:
        type: User
        description: "updated by"
      deleted_by:
        type: User
        description: "deleted by"
