QueryCommon:
  type: object
  config:
    fields:
      Categories:
        type: "[Category]"
        args:
          lang:
            description: 'Language code (e.g., en, cs)'
            type: 'String'
            defaultValue: 'cs'
        resolve: "@=service('getCategories')"
      Texts:
        type: "[Text]"
        args:
          id:
            description: 'id'
            type: 'String'
          lang:
            description: 'Language code (e.g., en, cs)'
            type: 'String'
            defaultValue: 'cs'
        resolve: "@=service('getTexts')"
      Own:
        type: "User"
        resolve: "@service('getOwn')"
      FilteredCategories:
        type: "[Category]"
        args:
          lang:
            description: 'Language code (e.g., en, cs)'
            type: 'String'
            defaultValue: 'cs'
        resolve: "@=service('getFilteredCategories')"
      FilteredTexts:
        type: "[Text]"
        args:
          category:
            description: 'category name'
            type: 'String'
          lang:
            description: 'Language code (e.g., en, cs)'
            type: 'String'
            defaultValue: 'cs'
        resolve: "@=service('getFilteredTexts')"
