Text:
  type: object
  config:
    description: "Text" 
    fields:
      id:
        type: String!
        description: "The ID of the Text"
      create_date:
        type: DateTime
        description: "Create date"
      last_update:
        type: DateTime
        description: "last update date"
      delete_date:
        type: DateTime
        description: "Delete date"
      title:
        type: String
        description: "title"
      title_en:
        type: String
        description: "title"
      text:
        type: String
        description: "text"
      text_en:
        type: String
        description: "text"
      author:
        type: String
        description: "author"
      source:
        type: String
        description: "source"
      category:
        type: Category
        description: "category"
      comments:
        type: "[Comment]"
        description: "comments"
      created_by:
        type: User
        description: "created by"
      updated_by:
        type: User
        description: "updated by"
      deleted_by:
        type: User
        description: "deleted by"
